version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    target-branch: "dependabot"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "dependabot"
    schedule:
      interval: "daily"
