# Generated by Django 5.0.1 on 2024-01-14 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='owner',
        ),
    ]
