# Generated by Django 5.0.1 on 2024-01-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_remove_room_owner'),
    ]

    operations = [
    ]
