# Generated by Django 5.0.1 on 2024-01-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_script'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Script',
        ),
    ]
