# Generated by Django 5.0.1 on 2024-01-19 09:33

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_script_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=0, editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
    ]
